services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: pass1234
      MYSQL_DATABASE: sss_test
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
